### ISSUE TITLE
いいね機能の設計をして、issueに分割する

### ISSUE THREAD

**Issue by ochi-sho-private-study** [ok-os-job-change-team/tetsuya-twitter-clone-bootcamp#22]

**Comment by kawabuchi-tetsuya** [comment]
## Favoriteモデルを実装する
- ER図を作成する
- Favoritesテーブルを実装する
  - favorite.schemaを作成・記述し、 `rake ridgepole:apply` を実行する
  - 必要そうなカラム
    - id (auto)
    - user_id
    - post_id
    - created_at
- Favoriteモデルを実装する
  - バリデーションを実装する
    - presence
    - belongs_to
      - Userモデル
      - Postモデル

**Comment by kawabuchi-tetsuya** [comment]
## FavoritesControllerを実装する
- FavoritesControllerを実装する
  - create
  - destroy
- 対応するrequests specを実装する
- Postsのindexおよびshowビューに、お気に入り登録・解除ボタンを実装する
