### ISSUE TITLE
フォロー機能の設計を設計をしてissueに落とし込む

### ISSUE THREAD

**Issue by ochi-sho-private-study** [ok-os-job-change-team/tetsuya-twitter-clone-bootcamp#24]

**Comment by kawabuchi-tetsuya** [comment]
# 要件
- current_userが、他のuserをフォローできる
- current_userが、フォロー中のuserをフォロー解除できる
- 各userのフォロー数・フォロワー数が確認できる
- 各userのフォロー・フォロワーが確認できる

# 作業内容
## 中間テーブルを作成する
- Relationshipsテーブルを作成する
  - relationship.schemaを作成・記述し、 `rake ridgepole:apply` を実行する
  - 必要そうなカラム
    - id (PK, auto)
    - follower_id (FK, フォローしたユーザーID）
    - followed_id (FK, フォローされたユーザーID）
    - created_at
- ER図を更新する

## モデルを作成する
- Relationshipモデルを作成する
  - Userモデルとリレーションを設定する

## ルーティングを設定する
- usersにネストする
- フォロー一覧にアクセスできるようにする
- フォロワー一覧にアクセスできるようにする

## コントローラーを作成する
- RelationshipsControllerを作成する
  - create
  - destroy
  - followings
  - followers

## ビューを整える
- 新規
  - フォロー一覧画面
  - フォロワー一覧画面
- 既存
  - ユーザー詳細画面
    - フォロー登録・解除ボタン (current_user以外)
    - フォロー数 (フォロー一覧画面へリンク)
    - フォロワー数 (フォロワー一覧画面へリンク)
  - ユーザー一覧画面
    - 詳細画面と同様
